---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vyos-iso-dv
  namespace: vyos
spec:
  source:
    http:
      url: https://downloads.vyos.io/rolling/current/amd64/vyos-rolling-latest.iso
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
